fix: revert dict back to protobuf in the iam binding update (#1838)
* fix: update the iam binding update logic

This is needed as some recent updates to a dependency (google-cloud-resource-manager or its dependencies) broke the existing logic, and we are seeing the
error like this:
--> policy.bindings.append(new_binding)
TypeError: Expected a message object, but got {'role': 'roles/run.invoker', 'members': [...]}

* use right import

* add unit test mocking the iam update method

* use mock bq connection client

* import module rephrasing